#FROM python:3.9-slim

#WORKDIR /app

#COPY requirments.txt . 
#RUN pip install --no-cache-dir -r requirments.txt

#COPY ./data /app/data
#CMD ["python", "app.py"]





FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files
COPY . .

# Run the Dash app
CMD ["python", "app.py"]